import type { CompetencyDiscipline } from "./types";
import { RN_SCALE } from "./types";

export const rnDiscipline: CompetencyDiscipline = {
  id: "rn",
  label: "RN",
  formTitle: "Skills Core Competency Checklist for Registered Nurse",
  scaleOptions: RN_SCALE,
  employeeLabel: "RN Name",
  evaluatorLabel: "Competency Assessed By",
  items: [
    { id: "temp", label: "System Assessments — Temperature" },
    { id: "pulse_radial_apical", label: "System Assessments — Pulse (Radial and Apical)" },
    { id: "respirations", label: "System Assessments — Respirations" },
    { id: "blood_pressure", label: "System Assessments — Blood Pressure" },
    { id: "pulse_oximetry", label: "System Assessments — Pulse Oximetry" },
    { id: "weight", label: "System Assessments — Weight" },
    { id: "respiratory", label: "System Assessments — Respiratory" },
    { id: "cardiovascular", label: "System Assessments — Cardiovascular" },
    { id: "digestive_gi", label: "System Assessments — Digestive / Gastrointestinal" },
    { id: "endocrine", label: "System Assessments — Endocrine" },
    { id: "nutrition", label: "System Assessments — Nutrition" },
    { id: "neuro_emotional", label: "System Assessments — Neurological / Emotional" },
    { id: "pain", label: "System Assessments — Pain" },
    { id: "musculoskeletal", label: "System Assessments — Musculoskeletal" },
    { id: "sensory", label: "System Assessments — Sensory" },
    { id: "functional_limitations", label: "System Assessments — Functional Limitations" },
    { id: "ent_eyes", label: "System Assessments — Ears / Nose / Throat / Eyes" },
    { id: "integumentary", label: "System Assessments — Integumentary" },
    { id: "teaching_disease_process", label: "Teaching — Disease Process" },
    { id: "teaching_diet_nutrition", label: "Teaching — Diet / Nutrition" },
    { id: "teaching_medication", label: "Teaching — Medication" },
    { id: "teaching_diabetic_management", label: "Teaching — Diabetic Management" },
    { id: "wound_sterile", label: "Wound Care — Sterile" },
    { id: "wound_nonsterile", label: "Wound Care — Non-sterile" },
    { id: "wound_vac", label: "Wound Care — Wound Vac" },
    { id: "wound_measuring", label: "Wound Care — Wound Measuring" },
    { id: "venipuncture_lab_draws", label: "Patient Care — Venipuncture / Lab Draws" },
    { id: "specimen_collection", label: "Patient Care — Specimen Collection" },
    { id: "catheter_care", label: "Patient Care — Catheter Care" },
    { id: "foley_insertion", label: "Patient Care — Foley Insertion" },
    { id: "replace_suprapubic", label: "Patient Care — Replace Suprapubic" },
    { id: "care_of_gtube", label: "Patient Care — Care of G-tube" },
    { id: "blood_glucometer_use", label: "Patient Care — Blood Glucometer Use" },
    { id: "care_of_jp_drain", label: "Patient Care — Care of JP Drain" },
    { id: "suture_removal", label: "Patient Care — Suture Removal" },
    { id: "staple_removal", label: "Patient Care — Staple Removal" },
    { id: "incentive_spirometry", label: "Patient Care — Incentive Spirometry" },
    { id: "colostomy_care", label: "Patient Care — Colostomy Care" },
    { id: "ileostomy_care", label: "Patient Care — Ileostomy Care" },
    { id: "ileal_conduit_care", label: "Patient Care — Ileal Conduit Care" },
    { id: "cast_care", label: "Patient Care — Cast Care" },
    { id: "use_of_splints", label: "Patient Care — Use of Splints" },
    { id: "safe_transfer_techniques", label: "Patient Care — Safe Transfer Techniques" },
    { id: "assistive_walker", label: "Assistive Devices — Walker" },
    { id: "assistive_cane", label: "Assistive Devices — Cane" },
    { id: "assistive_wheelchair", label: "Assistive Devices — Wheelchair" },
    { id: "assistive_crutches", label: "Assistive Devices — Crutches" },
    { id: "med_oral", label: "Medication Administration — Oral" },
    { id: "med_intramuscular", label: "Medication Administration — Intramuscular" },
    { id: "med_subcutaneous", label: "Medication Administration — Subcutaneous" },
    { id: "med_eye_drops", label: "Medication Administration — Eye Drops" },
    { id: "med_ear_drops", label: "Medication Administration — Ear Drops" },
    { id: "med_nose_drops", label: "Medication Administration — Nose Drops" },
    { id: "med_enteral_feedings", label: "Medication Administration — Enteral Feedings" },
    { id: "med_inhaled", label: "Medication Administration — Inhaled Medications" },
    { id: "oxygen_therapy", label: "Medication Administration — Oxygen Therapy" },
    { id: "nebulizer_therapy", label: "Medication Administration — Nebulizer Therapy" },
    { id: "iv_therapy", label: "Medication Administration — IV Therapy (if applicable)" },
    { id: "ic_universal_precautions", label: "Infection Control — Universal Precautions" },
    { id: "ic_hand_washing", label: "Infection Control — Hand Washing" },
    { id: "ic_bag_technique", label: "Infection Control — Bag Technique" },
    { id: "ic_glove_use", label: "Infection Control — Glove Use" },
    { id: "ic_biohazard_waste", label: "Infection Control — Biohazard Waste" },
    { id: "ic_sharps_disposal", label: "Infection Control — Sharps Disposal" },
    { id: "ic_specimen_transport", label: "Infection Control — Specimen Transport" },
    { id: "doc_admission_paperwork", label: "Documentation — Admission Paperwork" },
    { id: "doc_care_plan", label: "Documentation — Care Plan Development" },
    { id: "doc_visit_notes", label: "Documentation — Visit Notes" },
    { id: "supervision_lpn", label: "Supervisory Visits — LPN" },
    { id: "supervision_cna", label: "Supervisory Visits — CNA" },
    { id: "supervision_cmt", label: "Supervisory Visits — CMT" },
  ],
};