import {
  ADDRESS_LINE_CITY,
  ADDRESS_LINE_STREET,
  EMAIL_INTAKE,
  FAX_DISPLAY,
  PHONE_DISPLAY,
  TEL,
} from "@/components/marketing/marketing-constants";

/** Privacy Policy — website, Saintly Phone mobile app, and related services. */
export function PrivacyPolicyContent() {
  return (
    <>
      <p className="shh-legal-lead">
        Saintly Home Health LLC (&quot;Saintly,&quot; &quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is committed to
        protecting privacy. This Privacy Policy explains how we collect, use, and safeguard information when you use our
        public website, the Saintly Phone mobile application, the staff web workspace, and related communications.
      </p>

      <h2>Who we are</h2>
      <p>
        <strong>Saintly Home Health LLC</strong>
        <br />
        {ADDRESS_LINE_STREET}
        <br />
        {ADDRESS_LINE_CITY}
        <br />
        Phone:{" "}
        <a className="text-sky-800 underline-offset-2 hover:underline" href={TEL}>
          {PHONE_DISPLAY}
        </a>
        <br />
        Email:{" "}
        <a className="text-sky-800 underline-offset-2 hover:underline" href={`mailto:${EMAIL_INTAKE}`}>
          {EMAIL_INTAKE}
        </a>
      </p>

      <h2>Information we collect and handle</h2>
      <p>Depending on how you interact with us, we may collect or process categories of information such as:</p>
      <ul>
        <li>
          <strong>Contact and account data:</strong> name, email, phone number, account identifiers, and login/session
          information for authorized staff.
        </li>
        <li>
          <strong>Communications content and metadata:</strong> phone numbers, call and message content where applicable,
          voicemail, timestamps, duration, delivery status, and similar metadata needed to operate calling and messaging.
        </li>
        <li>
          <strong>Lead and CRM data:</strong> information about prospective patients, referral sources, and related
          workflow fields entered by staff or received through approved channels.
        </li>
        <li>
          <strong>Device and push data:</strong> device identifiers, mobile advertising/analytics tokens only if used
          by integrated services as configured, and push notification registration tokens used to deliver alerts.
        </li>
        <li>
          <strong>Operational and security logs:</strong> diagnostic or security-related logs generated by our systems
          and vendors (for example authentication events or error reports), limited to what is needed to operate and
          secure the service.
        </li>
        <li>
          <strong>Website and form data:</strong> information you submit through contact, intake, referral, or
          employment forms.
        </li>
      </ul>
      <p>
        Protected or health-related information may be handled in the course of providing healthcare communications and
        operations, subject to applicable law and our agreements with service providers. We do not use this Policy to
        replace any notice of privacy practices or agreement that applies to a specific regulated relationship.
      </p>

      <h2>How we use information</h2>
      <p>We use information to:</p>
      <ul>
        <li>Provide and operate Saintly Phone, the web workspace, calling, SMS, voicemail, and lead workflows</li>
        <li>Coordinate home health services with patients, families, and authorized providers</li>
        <li>Authenticate staff, enforce access rules, and protect accounts</li>
        <li>Provide support, troubleshoot issues, and improve reliability</li>
        <li>Meet legal, regulatory, and contractual obligations</li>
      </ul>
      <p>
        Overall, collected information is used for app and service functionality, communication with you as needed for
        those services, day-to-day operations, support, security, and legal and compliance requirements—not for the
        advertising or tracking practices described under <strong>Tracking and advertising</strong> below.
      </p>

      <h2>Tracking and advertising</h2>
      <p>
        Saintly does not use personal data for cross-app tracking, targeted advertising, or sharing with data brokers.
        Information collected through the app is used for app functionality, communication, operational purposes, security,
        support, and legal and compliance obligations, as described in this Policy.
      </p>

      <h2>Linking to identity</h2>
      <p>
        Many categories of data are linked to your staff account or device when you use Saintly Phone or the workspace.
        Operational logs may identify accounts or devices as needed for security and support. Public website visitors who
        only browse or submit a form may be identified only to the extent they provide contact details.
      </p>

      <h2>Service providers</h2>
      <p>
        We use vendors for hosting, authentication, telephony and messaging (including cloud communications providers),
        push notifications, and other functions required to run the app. Those providers process data on our behalf
        according to contractual terms and only as needed to deliver the services we configure. We do not permit
        service providers to use personal data for their own advertising or marketing purposes.
      </p>

      <h2>SMS and messaging</h2>
      <p>
        We may send SMS or similar messages for care coordination, scheduling, operational alerts, and follow-up, in
        accordance with consent where required. Message frequency may vary. Message and data rates may apply. You may opt
        out of marketing or non-essential SMS where applicable by following instructions in the message (for example,
        replying STOP where supported). Reply HELP where offered for assistance. Consent to receive SMS is not a condition
        of purchase for unrelated goods or services. We do not sell or share SMS consent or phone numbers with third
        parties for their own marketing.
      </p>

      <h2>Analytics, diagnostics, and cookies</h2>
      <p>
        Our website and apps may use cookies or similar technologies for basic operation and to understand usage in
        responsible ways. We may collect limited usage and diagnostic data—such as app interactions, crash reports,
        performance metrics, and security-related logs—to support reliability, performance, security, and service
        improvement. This data is not used for advertising or cross-app tracking.
      </p>

      <h2>Data security</h2>
      <p>
        We take reasonable administrative, technical, and organizational measures to protect information. No method of
        transmission or storage is completely secure.
      </p>

      <h2>Your rights and choices</h2>
      <p>
        Depending on applicable law, you may have rights to access, correct, or delete certain information, or to
        object to certain processing. To exercise rights or ask questions, contact us using the information below. We
        may need to verify your identity before fulfilling a request.
      </p>

      <h2>Children</h2>
      <p>
        Our services are not directed to children for independent use. Staff tools are intended for authorized adult
        users acting in their employment or contractual role.
      </p>

      <h2>Changes to this Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. The revised version will be posted on this page with an
        updated effective date.
      </p>

      <h2>Contact (including privacy questions)</h2>
      <p>
        Saintly Home Health LLC
        <br />
        {ADDRESS_LINE_STREET}, {ADDRESS_LINE_CITY}
        <br />
        {PHONE_DISPLAY}
        <br />
        Fax: {FAX_DISPLAY}
        <br />
        {EMAIL_INTAKE}
      </p>
      <p>
        For product support, see also our{" "}
        <a className="text-sky-800 underline-offset-2 hover:underline" href="/support">
          Support
        </a>{" "}
        page.
      </p>
    </>
  );
}
