import "server-only";

/** Common ZIP → city/state hints (AZ metro + selected US). Used to validate or enrich contact ZIPs. */
const ZIP_CITY_STATE: Record<string, { city: string; state: string }> = {
  "85001": { city: "Phoenix", state: "AZ" },
  "85004": { city: "Phoenix", state: "AZ" },
  "85006": { city: "Phoenix", state: "AZ" },
  "85008": { city: "Phoenix", state: "AZ" },
  "85012": { city: "Phoenix", state: "AZ" },
  "85013": { city: "Phoenix", state: "AZ" },
  "85014": { city: "Phoenix", state: "AZ" },
  "85015": { city: "Phoenix", state: "AZ" },
  "85016": { city: "Phoenix", state: "AZ" },
  "85017": { city: "Phoenix", state: "AZ" },
  "85018": { city: "Phoenix", state: "AZ" },
  "85020": { city: "Phoenix", state: "AZ" },
  "85021": { city: "Phoenix", state: "AZ" },
  "85022": { city: "Phoenix", state: "AZ" },
  "85023": { city: "Phoenix", state: "AZ" },
  "85024": { city: "Phoenix", state: "AZ" },
  "85027": { city: "Phoenix", state: "AZ" },
  "85028": { city: "Phoenix", state: "AZ" },
  "85029": { city: "Phoenix", state: "AZ" },
  "85031": { city: "Phoenix", state: "AZ" },
  "85032": { city: "Phoenix", state: "AZ" },
  "85033": { city: "Phoenix", state: "AZ" },
  "85034": { city: "Phoenix", state: "AZ" },
  "85035": { city: "Phoenix", state: "AZ" },
  "85037": { city: "Phoenix", state: "AZ" },
  "85040": { city: "Phoenix", state: "AZ" },
  "85041": { city: "Phoenix", state: "AZ" },
  "85042": { city: "Phoenix", state: "AZ" },
  "85043": { city: "Phoenix", state: "AZ" },
  "85044": { city: "Phoenix", state: "AZ" },
  "85045": { city: "Phoenix", state: "AZ" },
  "85048": { city: "Phoenix", state: "AZ" },
  "85050": { city: "Phoenix", state: "AZ" },
  "85051": { city: "Phoenix", state: "AZ" },
  "85053": { city: "Phoenix", state: "AZ" },
  "85054": { city: "Phoenix", state: "AZ" },
  "85201": { city: "Mesa", state: "AZ" },
  "85202": { city: "Mesa", state: "AZ" },
  "85203": { city: "Mesa", state: "AZ" },
  "85204": { city: "Mesa", state: "AZ" },
  "85205": { city: "Mesa", state: "AZ" },
  "85206": { city: "Mesa", state: "AZ" },
  "85207": { city: "Mesa", state: "AZ" },
  "85208": { city: "Mesa", state: "AZ" },
  "85209": { city: "Mesa", state: "AZ" },
  "85210": { city: "Mesa", state: "AZ" },
  "85212": { city: "Mesa", state: "AZ" },
  "85213": { city: "Mesa", state: "AZ" },
  "85215": { city: "Mesa", state: "AZ" },
  "85224": { city: "Chandler", state: "AZ" },
  "85225": { city: "Chandler", state: "AZ" },
  "85226": { city: "Chandler", state: "AZ" },
  "85248": { city: "Chandler", state: "AZ" },
  "85249": { city: "Chandler", state: "AZ" },
  "85281": { city: "Tempe", state: "AZ" },
  "85282": { city: "Tempe", state: "AZ" },
  "85283": { city: "Tempe", state: "AZ" },
  "85284": { city: "Tempe", state: "AZ" },
  "85250": { city: "Scottsdale", state: "AZ" },
  "85251": { city: "Scottsdale", state: "AZ" },
  "85254": { city: "Scottsdale", state: "AZ" },
  "85255": { city: "Scottsdale", state: "AZ" },
  "85257": { city: "Scottsdale", state: "AZ" },
  "85258": { city: "Scottsdale", state: "AZ" },
  "85259": { city: "Scottsdale", state: "AZ" },
  "85260": { city: "Scottsdale", state: "AZ" },
  "85262": { city: "Scottsdale", state: "AZ" },
  "85266": { city: "Scottsdale", state: "AZ" },
  "85301": { city: "Glendale", state: "AZ" },
  "85302": { city: "Glendale", state: "AZ" },
  "85303": { city: "Glendale", state: "AZ" },
  "85304": { city: "Glendale", state: "AZ" },
  "85305": { city: "Glendale", state: "AZ" },
  "85306": { city: "Glendale", state: "AZ" },
  "85308": { city: "Glendale", state: "AZ" },
  "85310": { city: "Glendale", state: "AZ" },
  "85345": { city: "Peoria", state: "AZ" },
  "85381": { city: "Peoria", state: "AZ" },
  "85382": { city: "Peoria", state: "AZ" },
  "85383": { city: "Peoria", state: "AZ" },
  "85374": { city: "Surprise", state: "AZ" },
  "85379": { city: "Surprise", state: "AZ" },
  "85323": { city: "Avondale", state: "AZ" },
  "85392": { city: "Avondale", state: "AZ" },
  "85338": { city: "Goodyear", state: "AZ" },
  "85395": { city: "Goodyear", state: "AZ" },
  "68114": { city: "Omaha", state: "NE" },
  "68116": { city: "Omaha", state: "NE" },
  "68118": { city: "Omaha", state: "NE" },
  "68124": { city: "Omaha", state: "NE" },
  "68131": { city: "Omaha", state: "NE" },
  "68134": { city: "Omaha", state: "NE" },
  "68144": { city: "Omaha", state: "NE" },
  "68154": { city: "Omaha", state: "NE" },
};

export function normalizeZip(raw: string): string {
  const m = raw.match(/\b(\d{5})(?:-\d{4})?\b/);
  return m?.[1] ?? raw.replace(/\D/g, "").slice(0, 5);
}

export function lookupZipCityState(zip: string): { city: string; state: string } | null {
  const z = normalizeZip(zip);
  if (z.length !== 5) return null;
  return ZIP_CITY_STATE[z] ?? null;
}
