import "server-only";

/**
 * Columns needed by `/admin/employees/[id]` (snapshot UI, role inference, activation gates).
 * Keeps payloads smaller than `select("*")` while matching prior behavior for displayed fields.
 */
export const APPLICANTS_ADMIN_DETAIL_COLUMNS = [
  "id",
  "first_name",
  "last_name",
  "email",
  "phone",
  "address",
  "city",
  "state",
  "zip",
  "position",
  "primary_discipline",
  "license_number",
  "years_experience",
  "preferred_hours",
  "availability_start_date",
  "work_setting",
  "type_of_position",
  "educational_level",
  "has_reliable_transportation",
  "can_provide_transportation",
  "drivers_license_state",
  "drivers_license_expiration_date",
  "auto_insurance_file",
  "license_certification_number",
  "license_issuing_state",
  "license_expiration_date",
  "cpr_bls_status",
  "cpr_expiration_date",
  "other_certifications",
  "has_conviction",
  "conviction_explanation",
  "has_license_discipline",
  "license_discipline_explanation",
  "needs_accommodation",
  "accommodation_explanation",
  "attestation_full_name",
  "attestation_date",
  "attestation_acknowledged",
  "status",
  "created_at",
  "updated_at",
  "resume_url",
  /** `buildApplicantRoleFieldsFromRecord` */
  "position_applied",
  "discipline",
  "job_title",
  "title",
  "role",
  "role_title",
].join(", ");
